name: bill_generator
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_slidable: ^0.5.7
  # create pdf document
  pdf: ^3.1.0
  rflutter_alert: ^2.0.2
  # save file
  path_provider: ^2.0.1

  # open pdf document
  open_file: ^3.1.0

  # format dates for invoice
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  